---
abstract: 'Logging class used by EntityModel'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Log
requires:
  Data::Dump: 0
  Exporter: 0
  IO::Handle: 0
  List::Util: 0
  POSIX: 0
  Time::HiRes: 0
  parent: 0
  perl: 5.010
version: 0.003
